language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run cov
env:
  global:
    # FIREBASE_TOKEN
    - secure: pu+tm6/iCvtRmdWKC500Bkn1iIIa2NHWww7S/Hp94gc8QHwegjEOQr2tyqojhgHspZ3E+TQ/z0jcNz/HZUgeSVoAHBkJTi2D0HAETIClvdin1503K50ORCbi/rvt7s9h1+QPaRDc+7YvGZnJHvPjgb/V9m0dZWWmzG6JmSkMt9x2h6vuIBAHmRWc/i+hXqLQBTNNHBhIa2zORNLf5Ez9wOErDK182UN5D2lW1wavrmi/92Gm74JPiI7upbmSnpPbY5DTAkf0yrTcSO68d8HEjLUXTs3DHPafXFhB+WcoNFMk8bU4Vbtf9RwuFtomeBEkQWiqQr5Q1ME0nOFUaqKO71zpESLseoo6asmJvytPcU6uu43Zfds1nPXcQhOIFHYXm329bHpzQyvrSRH36J4+xHXBK1v4KkxweChWgEOdFnsutP47Zgja1uNipjmpLgDzalcDuMO2jSjmO6kjwF2o62+TzXnPcQU64UYK9YIbzOe/J2VICo3fXj8yqKvJ7HI/7BzQFqLGc1aGU2H0kVxiUqPxO9uZtmd7MGUCCfOLlmkxfDj0XGtUHbaK3VYpZEyQ4nH+A6X+6/QUeESOrDPb5l+RJMHJ1TGZ3/Hqbu5QeMspg3PIZbmfGEhho6REhiGly1JHaLQLN7tLWQREddKkN9HmLDx0XnuTdb7q/Cu3ivs=
    # FIREBASE_SECRET
    - secure: yONgb1uChNVc7+SKQvnZrQjX04jFp+O0V6So/wz371yv01OpZbKVhhkWzd0p0IJqSaVGc/+PcyB+oT37QzDHRN2ZAUcY2ESOT1BW6w2G3Ukr5B6gu/Wst75mldr44WeGs5WTDfua59t23CGz8iG5RFK6/C3p92Jtxmjr6MjxWxtQd3ok92rqLUBxz1OXiCKoQPxK2TBiL926r72OK9dnSFbo5bg4O5/DJ1pTiS/p1j8t8tWlu5dzku+W9IfyFRWQGQJBBiaUbg0QmZYEyFx1UMlYtuxU8ZwXKgEUiSOfOlVJQJY7kzoGSWlTK9YGemYdxfXypoPKBYkKNYs+FPnukov/pGJ9Q5czdJ07PsqHGstC4yzdHlqHSzWUoHoZDWPfp0MhcbR16MarcKOrET/xhscN3SdLKqPH+INJAa+RGnJx+k2sftaHmKjxoaZ8U8lw6iKG+Y2oLKY3YimzAnjjOTTJgWvoAv/SUxICExsys1zK3+tXeCEafZAok7IXfydfVvdt45TwJsdYyB1C0b+OkQJjpuKXXFmaqWxJUHIreBHDl/MxZsCHJjhxGT2MTE4JG9lsTgJB1FDwvbf0K7187movnUFBeAxP+7D4tlay0kWonqlfonoMWbqZjqj0kcTxnDuDcxlrQggSvuvccj21Rnn8rFKbcAqjwsnnpN0TsNs=
